export const GET_MOVIE = "GET_MOVIE";
export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const GET_MOVIE_COMMENTS = "GET_MOVIE_COMMENTS";
export const GET_MOVIE_CASTS = "GET_MOVIE_CASTS";
export const ERROR_MOVIE = "ERROR_MOVIE";
